---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: maven
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: maven
    spec:
      nodeSelector:
          beta.kubernetes.io/instance-type: t2.medium
      containers:
        - name: maven
          image: maven:latest
          env:
            - name: JAVA_OPTS
              value: -Djenkins.install.runSetupWizard=false
          command: ["/bin/sh"]
          args: ["-c", "apt-get install git; wget https://github.com/getgauge/gauge/releases/download/v1.0.5/gauge-1.0.5-linux.x86_64.zip; unzip -o gauge-1.0.5-linux.x86_64.zip -d /usr/bin/local/; git config http.sslVerify false; git clone https://github.com/rohitverma1091/kubernetes-zalenium.git;ls -lrth; cd kubernetes-zalenium/DockerPoc/GaugeTest/; mvn test-compile gauge:execute -DspecsDir=specs -DinParallel=true -Dnodes=10 -f kubernetes-zalenium/DockerPoc/GaugeTest/pom.xml"]
